services:
  frontend:
    image: maknis3/eventmanager-frontend:latest
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend:5000
    networks:
      - eventmanager_network
    depends_on:
      - backend

  backend:
    image: maknis3/eventmanager-backend:latest
    environment:
      - MONGO_URI=mongodb://mongodb:27017/your_database_name
    networks:
      - eventmanager_network
    depends_on:
      - mongodb
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  mongodb:
    image: mongo:latest

    ports:
      - "27017:27017"
    networks:
      - eventmanager_network
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=your_database_name

networks:
  eventmanager_network:
    driver: overlay

volumes:
  mongodb_data:
    driver: local